services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: alpargatas_api
    ports:
      - "3000:3000"
    env_file:
      - .env

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: alpargatas_frontend
    ports:
      - "5173:80"
    depends_on:
      - api

  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    container_name: alpargatas_etl
    env_file:
      - .env
