services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_app
    ports:
      - "5173:80"
    depends_on:
      - api

  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    container_name: etl_pipeline
    env_file:
      - .env
    volumes:
      - ./etl/src:/app/src
      - ./etl/config:/app/config
    command: tail -f /dev/null

  model-training-pipeline:
    build:
      context: ./model-training-pipeline
      dockerfile: Dockerfile
    container_name: model_training_pipeline
    env_file:
      - .env
    volumes:
      - ./model-training-pipeline/src:/app/src
      - ./model-training-pipeline/config:/app/config
    command: tail -f /dev/null
