
export enum UF {
    ACRE = "AC",
    ALAGOAS = "AL",
    AMAPA = "AP",
    AMAZONAS = "AM",
    BAHIA = "BA",
    CEARA = "CE",
    ESPIRITO_SANTO = "ES",
    GOIAS = "GO",
    DISTRITO_FEDERAL = "DF",
    MARANHAO = "MA",
    MATO_GROSSO = "MT",
    MATO_GROSSO_SUL = "MS",
    MINAS_GERAIS = "MG",
    PARA = "PA",
    PARAIBA = "PB",
    PARANA = "PR",
    PERNAMBUCO = "PE",
    PIAUI = "PI",
    RIO_DE_JANEIRO = "RJ",
    RIO_GRANDE_NORTE = "RN",
    RIO_GRANDE_SUL = "RS",
    RONDONIA = "RO",
    RORAIMA = "RR",
    SANTA_CATARINA = "SC",
    SAO_PAULO = "SP",
    SERGIPE = "SE",
    TOCANTINS = "TO"
}