# ===================================================================
# ARQUIVO DE CONFIGURAÇÃO CENTRAL DO PIPELINE ALPargatas Insight
# ===================================================================
# Este arquivo contém todos os parâmetros, caminhos, e mapeamentos
# utilizados pelos jobs de ETL.

# --- 1. Caminhos de Dados (Relativos à raiz do projeto 'etl/') ---
paths:
  # Fontes de dados brutos
  raw_censo_escolar_zip: "data/censo_2023.zip"
  raw_municipios_brasileiros: "data/municipios_brasileiros.csv"

  # Fontes de dados brutos (pipeline do professor)
  raw_professor_dtb: "data/raw_professor/RELATORIO_DTB_BRASIL_2024_MUNICIPIOS.xls"
  raw_professor_ia_projetos: "data/raw_professor/Projetos_de_Atuac807a771o_-_IA_-_2020_a_2025.xlsx"
  raw_professor_ideb: "data/raw_professor/divulgacao_anos_iniciais_municipios_2023.xlsx"

  # Artefatos intermediários (camada "raw" do data lake)
  raw_escolas_paraiba: "data/raw/escolas_paraiba.parquet"

  # Artefatos processados (camada "processed" do data lake)
  processed_escolas: "data/processed/escolas_processado.parquet"
  processed_professor_auditoria: "data/processed/dados_temporais_para_auditoria.parquet"
  processed_professor_final: "data/processed/ENTREGAVEL_escolas_enriquecidas.parquet"

# --- 2. Configurações do Banco de Dados ---
database:
  db_name: "alpargatas_insight_db"
  escolas_collection_name: "escolas"
  # NOTA: A URI de conexão (com usuário/senha) continuará segura no arquivo .env

# --- 3. Configurações do Pipeline de Escolas (Principal) ---
escolas_pipeline:
  extract:
    # Parâmetros para filtrar o censo escolar
    filtro_uf: "PB"
    filtro_dependencia_adm: [1, 2, 3] # Federal, Estadual, Municipal
    filtro_situacao_funcionamento: 1 # Em atividade
    # Parâmetros para leitura do CSV
    csv_delimiter: ";"
    csv_encoding: "latin-1"

  transform:
    # Mapeamento de colunas do Censo para nomes padronizados
    column_map:
      CO_ENTIDADE: "escola_id_inep"
      NO_ENTIDADE: "escola_nome"
      CO_MUNICIPIO: "municipio_id_ibge"
      NO_MUNICIPIO: "municipio_nome"
      SG_UF: "estado_sigla"
      TP_DEPENDENCIA: "dependencia_adm"
      TP_LOCALIZACAO: "tipo_localizacao"
      QT_MAT_BAS: "total_alunos"
      IN_BIBLIOTECA: "possui_biblioteca"
      IN_INTERNET: "possui_internet"
      IN_AGUA_POTAVEL: "possui_agua_potavel"
      IN_ESGOTO_REDE_PUBLICA: "possui_saneamento_basico"
      IN_ENERGIA_REDE_PUBLICA: "possui_energia_publica"
      IN_QUADRA_ESPORTES: "possui_quadra_esportes"
      IN_ACESSIBILIDADE_INEXISTENTE: "acessibilidade_inexistente"

    # Mapeamento para valores categóricos
    categorical_maps:
      dependencia_adm:
        1: "Federal"
        2: "Estadual"
        3: "Municipal"
        4: "Privada"
      tipo_localizacao:
        1: "Urbana"
        2: "Rural"

    # Pesos para o cálculo do Score de Risco de Infraestrutura
    risk_score_weights:
      saneamento_basico: 25
      agua_potavel: 20
      biblioteca: 20
      internet: 15
      quadra_esportes: 10
      acessibilidade_pcd: 10
      pontuacao_maxima: 100

# --- 4. Configurações do Pipeline do Professor (Enriquecimento) ---
professor_pipeline:
  extract:
    # Configuração para extração cirúrgica das abas do Excel de projetos do IA
    ia_projetos_abas_config:
      "2020": { header: 5, iloc: [0, 1, 18, 20] }
      "2021": { header: 5, iloc: [0, 1, 25, 27] }
      "2022": { header: 5, iloc: [0, 1, 28, 30] }
      "2023": { header: 5, iloc: [0, 1, 34, 36] }
      "2024": { header: 5, iloc: [0, 1, 36, 38] }
      "2025": { header: 5, iloc: [0, 1, 36, 38] }
      "2022-Ed.Profissionalizante": { header: 5, usecols: "A,B,D,F" }
      "2023-Ed.Profissionalizante": { header: 5, usecols: "A,B,D,F" }
      "2024-Ed.Profissionalizante": { header: 5, usecols: "B,C,E,G" }
      "2025-Ed.Profissionalizante ": { header: 5, usecols: "B,C,E,G" }

  transform:
    # Lista de UFs válidas para o processamento
    valid_ufs: ["PB", "PE", "MG", "SP", "RJ"]
    # Mapeamento de siglas de UF para nomes completos
    uf_map:
      PB: "Paraíba"
      PE: "Pernambuco"
      MG: "Minas Gerais"
      SP: "São Paulo"
      RJ: "Rio de Janeiro"

    # Pesos para o cálculo do Score de Risco Contextualizado
    contextualized_score_weights:
      base_score_peso: 0.6
      ideb_score_peso: 0.4
