name: Build and Push Docker Images

on:
  push:
    branches: ["development"]
  workflow_dispatch:

jobs:
  build-and-push-images:
    name: Build & Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 1. Code Checkout
        uses: actions/checkout@v4

      - name: 2. Login in Github Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 3. Build and Push Backend Docker Image (API)
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: ghcr.io/ufpb-squad-team/alpargatas-api:latest

      - name: 4. Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: ghcr.io/ufpb-squad-team/alpargatas-frontend:latest
