name: Docker Build Sanity Check

on:
  pull_request:
    branches: ["main", "development"]
  workflow_dispatch:

jobs:
  build-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [server, client, etl]

    steps:
      - name: 1. Code Checkout
        uses: actions/checkout@v4

      - name: 2. Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 3. Build Docker image to check for errors
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service == 'client' && 'client' || matrix.service == 'server' && 'server' || 'etl' }}
          push: false
          load: false
