name: Build and Push Docker Images

on:
  push:
    branches: ["development"]
  workflow_dispatch:

jobs:
  build-and-push-images:
    name: Build & Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 1. Code Checkout
        uses: actions/checkout@v4

      - name: 2. Login in Github Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 3. Build and Push Backend Docker Image (API)
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: ghcr.io/ufpb-squad-team/alpargatas-api:latest

      - name: 4. Scan Backend Image for Vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/ufpb-squad-team/alpargatas-api:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"

      - name: 5. Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: ghcr.io/ufpb-squad-team/alpargatas-frontend:latest

      - name: 6. Scan Frontend Image for Vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/ufpb-squad-team/alpargatas-frontend:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
