name: Build, Push, and Deploy API

on:
  push:
    branches: ["development"]
  workflow_dispatch:

jobs:
  build-push-and-deploy:
    name: Build, Push & Deploy API
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: 1. Code Checkout
        uses: actions/checkout@v4

      - name: 2. Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::960196766146:role/GitHubActions-ECR-Access-Role
          aws-region: us-east-2

      - name: 3. Login in Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: 4. Build and push image to ECR
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: 960196766146.dkr.ecr.us-east-2.amazonaws.com/alpargatas-api:latest

      - name: 5. Deploy in EC2 Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            ./deploy.sh
