# .github/workflows/code_quality.yml

name: Verificador e Corretor de Qualidade do Código

on:
  pull_request:
    branches: ["main", "development"]
  workflow_dispatch:

jobs:
  lint-and-format-etl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./etl
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar dependências com Poetry
        run: poetry install --sync

      - name: Formatar e corrigir código com Ruff
        # Corrigido: Formata primeiro para resolver linhas longas, depois verifica e corrige o resto.
        run: poetry run ruff format . && poetry run ruff check . --fix

      - name: Fazer commit das alterações de formatação
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style(etl): Formata código Python automaticamente ✨"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"

  lint-and-format-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          # Corrigido: Usamos '**/package-lock.json' para encontrar o arquivo em qualquer subpasta
          cache-dependency-path: "**/package-lock.json"

      - name: Instalar dependências
        run: npm ci

      - name: Verificar código com ESLint
        run: npm run lint

      - name: Formatar código com Prettier
        run: npm run format

      - name: Fazer commit das alterações de formatação
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style(backend): Formata código TypeScript automaticamente ✨"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
