name: ETL Pipeline and Data Validation

on:
  push:
    branches:
      - "development"
  workflow_dispatch:

jobs:
  run-etl-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install ETL dependencies
        run: poetry install --sync --no-root
        working-directory: ./etl

      - name: Prepare Data Files for CI
        run: |
          curl -L "https://github.com/kelvins/Municipios-Brasileiros/raw/main/csv/municipios.csv" -o "./etl/data/municipios_brasileiros.csv"
          zip ./etl/data/censo_2023.zip ./etl/data/raw/escolas_paraiba_sample.parquet

      - name: Run ETL - Escolas Pipeline
        run: |
          poetry run python -m src.jobs.escolas_pipeline.extract
          poetry run python -m src.jobs.escolas_pipeline.transform
          poetry run python -m src.jobs.escolas_pipeline.validate
        working-directory: ./etl

      - name: Run ETL - Professor (Enrichment) Pipeline
        run: poetry run python -m src.jobs.enriquecimento_pipeline.main
        working-directory: ./etl
